### ISSUE TITLE
Channel locked logo everywhere

### ISSUE THREAD

**Issue by deadmau1** [arg0NNY/DiscordPlugins#112]
### Plugin:

📜 BetterChannelList

### Suggestion:

I don't know is this just with me or for everyone but there are locked channels logos showing to all channels, possible to hide it?
![image](https://github.com/user-attachments/assets/a82bc38b-8295-444a-9012-e32bcd0fd205)

**Comment by arg0NNY** [comment]
There will be no other way to tell if the channel is limited if this icon is disabled. However you're free to suggest an alternative.

**Comment by deadmau1** [comment]
![image](https://github.com/user-attachments/assets/dd04aa10-6104-48f4-8b6a-0e9290003dff)
By default there are no lock icons for channels just wanted to see channels as it is

**Comment by sirlupusdev** [comment]
The lock icon is embedded into the icon (on the left side), showing that the channel is restricted.

**Comment by deadmau1** [comment]
Ah, so it can't be hidden? i mean the lock icons

**Comment by sirlupusdev** [comment]
Not at the moment, but maybe we can add that as a toggle.

**Comment by deadmau1** [comment]
Gotcha Thank you

**Comment by sirlupusdev** [comment]
I _may_ have forgotten about this, feel free to mention me or comment if I do again.

**Comment by arg0NNY** [comment]
What's shown on the screenshot is expected behavior. Disabling the icons would leave no way of telling the channel properties without accessing its settings, which requires specific permissions on server.

I won't add the toggles to disable them since it will bloat the plugin's settings with no real benefit.

However, if you still want to disable the icons you can add this snippet to your Custom CSS in the BD settings:
```css
/* Hide "Limited" Icon */
.BCL--channel-name-icon:has(path[d~="0v24H48a16"]) {
    display: none;
}

/* Hide "NSFW" Icon */
.BCL--channel-name-icon:has(path[d~="188.09L149.35"]) {
    display: none;
}
```
